"use client";
import {lazy,Suspense,useCallback,useEffect,useRef,useState} from "react";
import {LogOut,Send,Archive,Trash2,Plus,LoaderCircle,ArrowLeft,Edit3,RefreshCw,LockKeyhole,ImageOff} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from "@/components/ui/alert-dialog";
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from "@/components/ui/select";
import {api,write,time} from "@/lib/client";
import type {Conversation,Message,Post} from "@/lib/types";
const HomepageManager=lazy(()=>import("@/components/homepage-manager"));
const PostEditor=lazy(()=>import("@/components/post-editor"));
export default function Admin(){
 const [authState,setAuthState]=useState<"loading"|"login"|"password"|"ready">("loading"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("inbox");
 const [username,setUsername]=useState("capone"),[password,setPassword]=useState(""),[newPassword,setNewPassword]=useState("");
 const [conversations,setConversations]=useState<Conversation[]>([]),[filter,setFilter]=useState("open"),[listMore,setListMore]=useState(false),[selected,setSelected]=useState<string|null>(null),[current,setCurrent]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[reply,setReply]=useState(""),[messageMore,setMessageMore]=useState(false);
 const [posts,setPosts]=useState<Post[]>([]),[postMore,setPostMore]=useState(false),[editor,setEditor]=useState<Post|null|undefined>(undefined);
 const [confirm,setConfirm]=useState<{title:string;action:()=>Promise<void>}|null>(null);
 const end=useRef<HTMLDivElement>(null),active=useRef<string|null>(null),older=useRef<Message[]>([]),pending=useRef({text:"",id:""});
 function fail(e:unknown){setError((e as Error).message||"操作未完成。")}
 async function loadMe(){try{const d=await api<{mustChangePassword:boolean}>("/api/admin/me");setAuthState(d.mustChangePassword?"password":"ready")}catch(e){if((e as {status:number}).status===401)setAuthState("login");else fail(e)}}
 useEffect(()=>{loadMe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/auth/sign-in/username",write("POST",{username,password}));setPassword("");await loadMe()}catch(e){fail(e)}finally{setBusy(false)}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/admin/password",write("POST",{currentPassword:password,newPassword}));setPassword("");setNewPassword("");setAuthState("ready");setNotice("密码已更新。");await loadMe()}catch(e){fail(e)}finally{setBusy(false)}}
 async function logout(){try{await api("/api/auth/sign-out",write("POST",{}));setAuthState("login");setSelected(null);setMessages([]);setConversations([]);setPosts([])}catch(e){fail(e)}}
 const loadConversations=useCallback(async(offset=0)=>{const d=await api<{conversations:Conversation[];hasMore:boolean}>("/api/admin/conversations?status="+filter+"&offset="+offset);setConversations(c=>offset?[...c,...d.conversations]:d.conversations);setListMore(d.hasMore)},[filter]);
 const loadDetail=useCallback(async(id:string)=>{const d=await api<{conversation:Conversation;messages:Message[];hasMore:boolean}>("/api/admin/conversations/"+id);if(active.current!==id)return;setCurrent(d.conversation);setMessages([...older.current.filter(m=>!d.messages.some(n=>n.id===m.id)),...d.messages]);setMessageMore(d.hasMore);if(d.conversation.unread)await api("/api/admin/conversations/"+id,write("PATCH",{action:"read",seenAt:d.conversation.updatedAt}))},[]);
 const loadPosts=useCallback(async(offset=0)=>{const d=await api<{posts:Post[];hasMore:boolean}>("/api/admin/posts?offset="+offset);setPosts(p=>offset?[...p,...d.posts]:d.posts);setPostMore(d.hasMore)},[]);
 useEffect(()=>{if(authState!=="ready")return;if(tab==="inbox")loadConversations().catch(fail);if(tab==="posts")loadPosts().catch(fail)},[authState,tab,loadConversations,loadPosts]);
 useEffect(()=>{if(authState!=="ready"||tab!=="inbox")return;const id=setInterval(()=>{if(document.hidden)return;loadConversations().catch(()=>{});if(active.current)loadDetail(active.current).catch(()=>{})},3000);return()=>clearInterval(id)},[authState,tab,loadConversations,loadDetail]);
 useEffect(()=>{active.current=selected;older.current=[];if(selected)loadDetail(selected).catch(fail);else{setMessages([]);setCurrent(null)}},[selected,loadDetail]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[messages.length]);
 async function previous(){if(!selected||!messages.length)return;try{const d=await api<{messages:Message[];hasMore:boolean}>("/api/admin/conversations/"+selected+"?before="+messages[0].createdAt);older.current=[...d.messages,...older.current];setMessages(m=>[...d.messages,...m]);setMessageMore(d.hasMore)}catch(e){fail(e)}}
 async function send(e:React.FormEvent){e.preventDefault();if(!selected||!reply.trim()||busy)return;setBusy(true);setError("");if(pending.current.text!==reply)pending.current={text:reply,id:crypto.randomUUID()};try{await api("/api/admin/conversations/"+selected,write("POST",{message:reply,requestId:pending.current.id}));setReply("");pending.current={text:"",id:""};await loadDetail(selected);await loadConversations()}catch(e){fail(e)}finally{setBusy(false)}}
 async function setStatus(){if(!selected||!current)return;await api("/api/admin/conversations/"+selected,write("PATCH",{status:current.status==="archived"?"open":"archived"}));setSelected(null);await loadConversations()}
 function deleteConversation(){if(!selected)return;setConfirm({title:"删除这条咨询及全部消息？此操作不可恢复。",action:async()=>{await api("/api/admin/conversations/"+selected,{method:"DELETE"});setSelected(null);await loadConversations()}})}
 function edit(p?:Post){setEditor(p||null);setError("")}
 async function togglePost(p:Post){await api("/api/admin/posts/"+p.id,write("PATCH",{...p,status:p.status==="published"?"draft":"published"}));await loadPosts()}
 function deletePost(p:Post){setConfirm({title:"删除“"+p.title+"”？此操作不可恢复。",action:async()=>{await api("/api/admin/posts/"+p.id,{method:"DELETE"});await loadPosts()}})}
 const passwordForm=<form className="account-form" onSubmit={changePassword}><h2>{authState==="password"?"设置你的新密码":"修改密码"}</h2><p className="muted">{authState==="password"?"首次登录，请更换初始密码后进入后台。":"更新后，其他设备上的登录会话将失效。"}</p><label>当前密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>新密码<input type="password" minLength={5} maxLength={128} autoComplete="new-password" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><p className="micro">最低5位，建议使用更长且不重复的密码。</p><button className="primary-button" disabled={busy}>更新密码</button></form>;
 if(authState!=="ready")return <main className="admin-login"><a className="wordmark" href="/">CAPONE<span>卡彭团队</span></a>{authState==="loading"?<div className="empty-state"><LoaderCircle className="spin"/><p>正在连接管理后台…</p>{error&&<button onClick={()=>{setError("");loadMe()}}>重试连接</button>}</div>:authState==="password"?passwordForm:<form className="account-form" onSubmit={login}><p className="eyebrow">PRIVATE STUDIO</p><h1>管理后台</h1><label>管理员账号<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-button" disabled={busy}><LockKeyhole size={16}/>{busy?"正在登录":"登录"}</button></form>}{error&&<p className="error-message" role="alert">{error}</p>}<a className="text-link" href="/"><ArrowLeft size={15}/> 返回网站</a></main>;
 return <main className="admin-shell"><header className="admin-header"><a className="wordmark" href="/">CAPONE<span>工作室管理</span></a><div><a href="/" className="text-link" target="_blank">查看网站</a><button className="icon-button" title="退出登录" aria-label="退出登录" onClick={logout}><LogOut size={19}/></button></div></header>
 {error&&<p className="admin-alert error-message" role="alert">{error}<button onClick={()=>setError("")}>关闭</button></p>}{notice&&<p className="admin-alert" role="status">{notice}<button onClick={()=>setNotice("")}>关闭</button></p>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="admin-tabs" variant="line"><TabsTrigger value="inbox">咨询收件箱</TabsTrigger><TabsTrigger value="posts">团队动态</TabsTrigger><TabsTrigger value="homepage">首页视频</TabsTrigger><TabsTrigger value="account">账号</TabsTrigger></TabsList>
 <TabsContent value="inbox"><div className={"inbox "+(selected?"has-selection":"")}><aside className="inbox-list"><div className="inbox-filter"><Select value={filter} onValueChange={v=>{setFilter(v);setSelected(null)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="open">进行中的咨询</SelectItem><SelectItem value="archived">已归档</SelectItem></SelectContent></Select><button className="icon-button" aria-label="刷新咨询" title="刷新咨询" onClick={()=>loadConversations().catch(fail)}><RefreshCw size={16}/></button></div>{!conversations.length&&<p className="empty-state">暂无{filter==="archived"?"已归档":"新的"}咨询。</p>}{conversations.map(c=><button key={c.id} className={"conversation-row "+(selected===c.id?"selected":"")} onClick={()=>{setMessages([]);setSelected(c.id);setReply("")}}><span><strong>{c.nickname||"访客"}</strong>{c.unread>0&&<b className="unread">{c.unread}</b>}</span><small>{c.sourceTitle||"直接咨询"}</small><time>{time(c.updatedAt)}</time></button>)}{listMore&&<button className="text-link load-more" onClick={()=>loadConversations(conversations.length).catch(fail)}>加载更多</button>}</aside>
 <section className="inbox-detail">{!selected?<div className="empty-state"><MessagePlaceholder/><h2>认真回应每一份信任。</h2><p>选择一条咨询，查看来信。</p></div>:<><header className="conversation-header"><button className="icon-button back-to-list" title="返回列表" aria-label="返回咨询列表" onClick={()=>setSelected(null)}><ArrowLeft size={18}/></button><div><h2>{current?.nickname||"访客"}</h2><p>{current?.contact||"未留联系方式"}</p>{current?.sourceTitle&&<small>来自：{current.sourceTitle}</small>}</div><button className="icon-button" title={current?.status==="archived"?"恢复会话":"归档会话"} aria-label={current?.status==="archived"?"恢复会话":"归档会话"} onClick={()=>setStatus().catch(fail)}><Archive size={18}/></button><button className="icon-button" title="删除会话" aria-label="删除会话" onClick={deleteConversation}><Trash2 size={18}/></button></header><div className="admin-messages">{messageMore&&<button className="text-link" onClick={previous}>查看更早消息</button>}{messages.map(m=><article className={"message "+(m.role==="admin"?"sent":"received")} key={m.id}><span className="message-label">{m.role==="visitor"?"客户":m.role==="auto"?"自动回复":"你"} · {time(m.createdAt)}</span>{m.sourceTitle&&<small>关于：{m.sourceTitle}</small>}<p>{m.body}</p></article>)}<div ref={end}/></div><form className="admin-compose" onSubmit={send}><textarea aria-label="回复客户" placeholder="回复这位客户…" value={reply} onChange={e=>setReply(e.target.value)} maxLength={2000} rows={3}/><button className="primary-button" disabled={busy||!reply.trim()}><Send size={16}/>{busy?"发送中":"发送回复"}</button></form></>}</section></div></TabsContent>
 <TabsContent value="posts"><div className="admin-section-heading"><h1>团队动态</h1><button className="primary-button" onClick={()=>edit()}><Plus size={18}/>新建帖子</button></div><div className="admin-post-list">{posts.map(p=><article key={p.id}><div className="admin-thumbnail">{p.kind==="video"?(p.posterUrl?<img src={p.posterUrl} alt={p.title+"封面"} loading="lazy"/>:<ImageOff size={24}/>):<img src={"/api/media/"+p.mediaId} alt="" loading="lazy"/>}</div><div><h2>{p.title}</h2><p>{p.status==="published"?"已发布":"草稿"} · {p.width>p.height?"16:9":"9:16"} · {time(p.createdAt)}</p></div><div className="post-actions"><button className="text-link" onClick={()=>togglePost(p).catch(fail)}>{p.status==="published"?"撤下":"发布"}</button><button className="icon-button" title="编辑帖子" aria-label={"编辑"+p.title} onClick={()=>edit(p)}><Edit3 size={18}/></button><button className="icon-button" title="删除帖子" aria-label={"删除"+p.title} onClick={()=>deletePost(p)}><Trash2 size={18}/></button></div></article>)}</div>{!posts.length&&<p className="empty-state">还没有帖子。</p>}{postMore&&<button className="text-link load-more" onClick={()=>loadPosts(posts.length).catch(fail)}>加载更多帖子</button>}</TabsContent>
 <TabsContent value="homepage"><Suspense fallback={<p className="empty-state">正在打开首页视频管理…</p>}>{tab==="homepage"&&<HomepageManager/>}</Suspense></TabsContent>
 <TabsContent value="account">{passwordForm}</TabsContent></Tabs>
 {editor!==undefined&&<Suspense fallback={<p role="status">正在打开动态编辑…</p>}><PostEditor key={editor?.id||"new"} post={editor} onClose={()=>setEditor(undefined)} onSaved={async()=>{await loadPosts();setNotice("帖子已保存。")}}/></Suspense>}
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent><AlertDialogTitle>确认删除</AlertDialogTitle><AlertDialogDescription>{confirm?.title}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm?.action().catch(fail);setConfirm(null)}}>删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
function MessagePlaceholder(){return <LockKeyhole size={26}/>}
