"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Send,LockKeyhole,LoaderCircle,ArrowUpRight} from "lucide-react";
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetHeader} from "@/components/ui/sheet";
import {api,time,write} from "@/lib/client";
import type {Message} from "@/lib/types";
export function Consultation({open,onOpenChange,onAfterClose,source}:{open:boolean;onOpenChange:(v:boolean)=>void;onAfterClose?:()=>void;source?:{id:string;title:string}|null}){
 const [messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[nickname,setNickname]=useState(""),[contact,setContact]=useState(""),[error,setError]=useState(""),[ready,setReady]=useState(false),[sending,setSending]=useState(false),[more,setMore]=useState(false);
 const bottom=useRef<HTMLDivElement>(null),pending=useRef({text:"",id:""}),older=useRef<Message[]>([]),initialized=useRef(false);
 const refresh=useCallback(async()=>{const d=await api<{messages:Message[];hasMore:boolean;conversation:{nickname:string;contact:string}|null}>("/api/chat");setMessages([...older.current.filter(m=>!d.messages.some(n=>n.id===m.id)),...d.messages]);setMore(d.hasMore);setReady(true);if(!initialized.current){setNickname(d.conversation?.nickname||"");setContact(d.conversation?.contact||"");initialized.current=true}},[]);
 useEffect(()=>{if(!open)return;refresh().catch(e=>setError(e.message));const id=setInterval(()=>{if(!document.hidden)refresh().catch(()=>{})},3000);return()=>clearInterval(id)},[open,refresh]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages.length,open]);
 useEffect(()=>{if(!open||!window.visualViewport)return;const update=()=>document.documentElement.style.setProperty("--chat-height",window.visualViewport!.height+"px");update();window.visualViewport.addEventListener("resize",update);return()=>window.visualViewport?.removeEventListener("resize",update)},[open]);
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim()||sending||!ready)return;setSending(true);setError("");if(pending.current.text!==text)pending.current={text,id:crypto.randomUUID()};try{await api("/api/chat",write("POST",{message:text,requestId:pending.current.id,nickname,contact,sourceId:source?.id||""}));setText("");pending.current={text:"",id:""};await refresh()}catch(e){setError((e as Error).message)}finally{setSending(false)}}
 async function previous(){try{const d=await api<{messages:Message[];hasMore:boolean}>("/api/chat?before="+messages[0]?.createdAt);older.current=[...d.messages,...older.current];setMessages(m=>[...d.messages,...m]);setMore(d.hasMore)}catch(e){setError((e as Error).message)}}
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="chat-panel" side="right" onCloseAutoFocus={onAfterClose}><SheetHeader className="chat-heading"><span className="eyebrow">PRIVATE CONVERSATION</span><SheetTitle>与你，一对一。</SheetTitle><SheetDescription>卡彭｜Mr. Capone · 先评估，后承接</SheetDescription></SheetHeader>
 <div className="chat-privacy"><LockKeyhole size={14}/> 仅你与团队可见 · 仅接待成年女性</div>
 {source&&<div className="chat-source">正在咨询：{source.title}</div>}
 <div className="chat-messages" aria-live="polite">{more&&<button className="text-link" onClick={previous}>查看更早消息</button>}{!messages.length&&<div className="chat-welcome"><p className="serif">每一段故事，都值得被认真倾听。</p><p>可以先说说你的处境与期待。无需注册，联系方式选填。离开页面后，我们的回复仍会保留在本浏览器的会话中。</p></div>}{messages.map(m=><article className={"message "+(m.role==="visitor"?"sent":"received")} key={m.id}><span className="message-label">{m.role==="visitor"?"你":m.role==="auto"?"接待助理 · 自动回复":"卡彭团队"} · {time(m.createdAt)}</span>{m.sourceTitle&&<small>关于：{m.sourceTitle}</small>}<p>{m.body}</p></article>)}<div ref={bottom}/></div>
 <form className="chat-compose" onSubmit={send}><div className="optional-fields"><input aria-label="称呼（选填）" placeholder="称呼（选填）" value={nickname} maxLength={80} onChange={e=>setNickname(e.target.value)}/><input aria-label="微信或 WhatsApp（选填）" placeholder="微信 / WhatsApp（选填）" value={contact} maxLength={200} onChange={e=>setContact(e.target.value)}/></div><label className="sr-only" htmlFor="visitor-message">你的留言</label><textarea id="visitor-message" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} rows={3} placeholder="说说你的情况与期待…" disabled={sending}/>{error&&<p role="alert" className="error-message">{error} {!ready&&<button type="button" onClick={()=>refresh().then(()=>setError("")).catch(e=>setError(e.message))}>重试连接</button>}</p>}<div className="compose-actions"><a href="https://wa.me/8619805071031" target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={13}/></a><button className="primary-button" disabled={!ready||sending||!text.trim()}>{sending?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>} {sending?"发送中":"发送留言"}</button></div></form></SheetContent></Sheet>
}
